### ISSUE TITLE
Reader failure

### ISSUE THREAD

**Issue by sadikovi** [sadikovi/spark-netflow#20]
Buffer reader fails with exception (file will be attached):

``` shell
16/03/14 09:22:17 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 57.0 (TID 4279, 143.96.25.150): java.lang.IllegalArgumentException: Unexpected EOF
    at com.github.sadikovi.netflowlib.Buffers$ScanRecordBuffer$1.next(Buffers.java:177)
    at com.github.sadikovi.netflowlib.Buffers$ScanRecordBuffer$1.next(Buffers.java:115)
    at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
    at scala.collection.Iterator$JoinIterator.next(Iterator.scala:194)
    at com.github.sadikovi.spark.rdd.NetFlowFileRDD$$anon$1.next(NetFlowFileRDD.scala:149)
    at com.github.sadikovi.spark.rdd.NetFlowFileRDD$$anon$1.next(NetFlowFileRDD.scala:147)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
    at org.apache.spark.sql.execution.aggregate.TungstenAggregationIterator.processInputs(TungstenAggregationIterator.scala:366)
    at org.apache.spark.sql.execution.aggregate.TungstenAggregationIterator.start(TungstenAggregationIterator.scala:622)
    at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1.org$apache$spark$sql$execution$aggregate$TungstenAggregate$$anonfun$$executePartition$1(TungstenAggregate.scala:110)
    at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:119)
    at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:119)
    at org.apache.spark.rdd.MapPartitionsWithPreparationRDD.compute(MapPartitionsWithPreparationRDD.scala:64)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
    at org.apache.spark.scheduler.Task.run(Task.scala:88)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: EOF, -1 bytes read
    at com.github.sadikovi.netflowlib.Buffers$ScanRecordBuffer$1.next(Buffers.java:157)
    ... 25 more
```

**Comment by sadikovi** [comment]
It seems that file is either empty or contains corrupt records, it is just 96 bytes.
